---
# tasks file for kubernetes/roles/kube_ka
- name: INSTALL keepalived
  yum:
    name: keepalived
    state: present

- name: MAKE NEEDED dirs
  file:
    path: /etc/keepalived
    state: directory
    mode: 0755

- name: COPY keepalived.conf.j2
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf mode=0664
  register: result

- name: START keepalived
  service: name=keepalived state=restarted enabled=yes
  when: result.changed
